services:
  espythonow:
    hostname: espnow-relay
    container_name: espnow-relay
    image: ladder99/espnow-relay:latest
    restart: unless-stopped
    command: /bin/bash -c '/app/enable_wireless_monitor_mode.sh && python3 -u main.py'
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=20
      - INTERFACE=wlxc01c3038d5a8
      - BROKER_IP=sharc.tech
      - BROKER_PORT=1883
      - BROKER_USERNAME=
      - BROKER_PASSWORD=
      - ESP_TO_BROKER_CUSTOM=1
      - BROKER_TO_ESP_CUSTOM=1
      - DROP_INCOMING_INVALID_PEER=1
    stop_grace_period: 10s
    stop_signal: SIGTERM
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "20m"

  dozzle:
    hostname: dozzle
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      - espnow
    ports:
      - "8080:8080/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "20m"

networks:
  espnow:
    name: espnow